In [1]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv("https://raw.githubusercontent.com/susanqisun/DAV-6150/master/assignments/investments_VC.csv",encoding = 'unicode_escape')
df

,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,...,secondary_market,product_crowdfunding,round_A,round_B,round_C,round_D,round_E,round_F,round_G,round_H
0,Exploco,http://www.exploco.com,|Adventure Travel|,Adventure Travel,-,operating,AUS,NaN,Perth,Perth,...,0,0,0,0,0,0,0,0,0,0
1,Rotor,http://rotor.ie/,|Developer Tools|Music|Video|,Video,-,operating,IRL,NaN,Dublin,Dublin,...,0,0,0,0,0,0,0,0,0,0
2,12 Labs,http://www.12labs.com/,|Personal Health|Health and Wellness|,Personal Health,-,operating,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,Shopboostr,http://shopboostr.de/,|SaaS|Reviews and Recommendations|E-Commerce|,SaaS,-,operating,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,The Urban Roosters,http://www.urbanroosters.com,NaN,NaN,-,operating,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49433,AndrewBurnett.com Ltd,http://www.andrewburnett.com,|Internet|SEO|Services|Public Relations|Social...,Internet,-,operating,GBR,NaN,Edinburgh,Edinburgh,...,0,0,0,0,0,0,0,0,0,0
49434,Buena Park Locksmith,http://www.BuenaParkLocksmithCA.com,|Local Businesses|,Local Businesses,-,operating,USA,CA,Anaheim,Buena Park,...,0,0,0,0,0,0,0,0,0,0
49435,Artifact Technologies,http://artifacttech.com,|Software|,Software,"8,61,030",operating,USA,WA,Seattle,Seattle,...,0,0,0,0,0,0,0,0,0,0
49436,Jumper Networks,http://www.jumpernetworks.com,|Web Development|Social Bookmarking|SEO|Knowle...,Social Bookmarking,-,closed,USA,MA,MA - Other,White Horse Beach,...,0,0,0,0,0,0,0,0,0,0
49437,test company,http://www.gmail2.com,NaN,NaN,"1,000",operating,ARE,NaN,Dubai,Dubai,...,0,0,0,0,0,0,0,0,0,0

In [14]:
# check the shape for the dataframe
df.shape

(49438, 38)

In [15]:
# statistical summary of numeric variables:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
funding_rounds,49438.0,1.696205e+00,1.294213e+00,1.0,1.0,1.0,2.0,1.800000e+01
founded_year,38482.0,2.007359e+03,7.579203e+00,1902.0,2006.0,2010.0,2012.0,2.014000e+03
seed,49438.0,2.173215e+05,1.056985e+06,0.0,0.0,0.0,25000.0,1.300000e+08
venture,49438.0,7.501051e+06,2.847112e+07,0.0,0.0,0.0,5000000.0,2.351000e+09
equity_crowdfunding,49438.0,6.163322e+03,1.999048e+05,0.0,0.0,0.0,0.0,2.500000e+07
undisclosed,49438.0,1.302213e+05,2.981404e+06,0.0,0.0,0.0,0.0,2.924328e+08
convertible_note,49438.0,2.336410e+04,1.432046e+06,0.0,0.0,0.0,0.0,3.000000e+08
debt_financing,49438.0,1.888157e+06,1.382046e+08,0.0,0.0,0.0,0.0,3.007950e+10
angel,49438.0,6.541898e+04,6.582908e+05,0.0,0.0,0.0,0.0,6.359026e+07
grant,49438.0,1.628453e+05,5.612088e+06,0.0,0.0,0.0,0.0,7.505000e+08
private_equity,49438.0,2.074286e+06,3.167231e+07,0.0,0.0,0.0,0.0,3.500000e+09
post_ipo_equity,49438.0,6.088736e+05,2.678348e+07,0.0,0.0,0.0,0.0,4.700000e+09
post_ipo_debt,49438.0,4.434360e+05,3.428169e+07,0.0,0.0,0.0,0.0,5.800000e+09
secondary_market,49438.0,3.845592e+04,3.864461e+06,0.0,0.0,0.0,0.0,6.806116e+08
product_crowdfunding,49438.0,7.074227e+03,4.282166e+05,0.0,0.0,0.0,0.0,7.200000e+07
round_A,49438.0,1.243955e+06,5.531974e+06,0.0,0.0,0.0,0.0,3.190000e+08
round_B,49438.0,1.492891e+06,7.472704e+06,0.0,0.0,0.0,0.0,5.420000e+08
round_C,49438.0,1.205356e+06,7.993592e+06,0.0,0.0,0.0,0.0,4.900000e+08
round_D,49438.0,7.375261e+05,9.815218e+06,0.0,0.0,0.0,0.0,1.200000e+09
round_E,49438.0,3.424682e+05,5.406915e+06,0.0,0.0,0.0,0.0,4.000000e+08
round_F,49438.0,1.697692e+05,6.277905e+06,0.0,0.0,0.0,0.0,1.060000e+09
round_G,49438.0,5.767067e+04,5.252312e+06,0.0,0.0,0.0,0.0,1.000000e+09
round_H,49438.0,1.423197e+04,2.716865e+06,0.0,0.0,0.0,0.0,6.000000e+08

In [17]:
df.groupby(['market']).count()

KeyError: 'market'